<?xml version="1.0" encoding="utf-8"?><Database Name="PBD" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DLEFTN6\MANSINVENTIVE;Initial Catalog=PBD;Integrated Security=True" SettingsObjectName="Proiect.Properties.Settings" SettingsPropertyName="PBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Enrollments" Member="Enrollments">
    <Type Name="Enrollment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idcourse" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Enrollment" Member="User" ThisKey="iduser" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Course_Enrollment" Member="Course" ThisKey="idcourse" OtherKey="id" Type="Course" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Subjects" Member="Subjects">
    <Type Name="Subject">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="subjectname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Subject_UsersSubject" Member="UsersSubjects" ThisKey="id" OtherKey="idsubject" Type="UsersSubject" />
      <Association Name="Subject_Course" Member="Courses" ThisKey="id" OtherKey="idSubject" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="request" Member="request1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="User_Request" Member="User" ThisKey="iduser" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userpass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="useremail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Enrollment" Member="Enrollments" ThisKey="id" OtherKey="iduser" Type="Enrollment" />
      <Association Name="User_Request" Member="Requests" ThisKey="id" OtherKey="iduser" Type="Request" />
      <Association Name="User_UsersSubject" Member="UsersSubjects" ThisKey="id" OtherKey="iduser" Type="UsersSubject" />
    </Type>
  </Table>
  <Table Name="dbo.UsersSubjects" Member="UsersSubjects">
    <Type Name="UsersSubject">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iduser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idsubject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Subject_UsersSubject" Member="Subject" ThisKey="idsubject" OtherKey="id" Type="Subject" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_UsersSubject" Member="User" ThisKey="iduser" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="coursename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="courseprof" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="coursepath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idSubject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Course_Enrollment" Member="Enrollments" ThisKey="id" OtherKey="idcourse" Type="Enrollment" />
      <Association Name="Subject_Course" Member="Subject" ThisKey="idSubject" OtherKey="id" Type="Subject" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>